# Generated by Django 5.0.4 on 2024-04-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0003_remove_estudiante_curso_remove_profesor_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Nombre del Curso', 'verbose_name_plural': 'Nombres del Curso'},
        ),
        migrations.AddField(
            model_name='curso',
            name='cant_max_alumnos',
            field=models.PositiveBigIntegerField(default=1000),
        ),
    ]
