# Generated by Django 5.0.4 on 2024-04-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0005_alter_curso_cant_max_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clase.curso'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clase.profesor'),
        ),
    ]
