# Generated by Django 5.0.4 on 2024-05-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0006_alter_comision_curso_alter_comision_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cedula_de_identidad',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='formacion_academica',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
    ]
