# Generated by Django 5.0.4 on 2024-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0007_estudiante_apellido_estudiante_cedula_de_identidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cedula_de_identidad',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profesor',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
